### ISSUE TITLE
Streaming API

### ISSUE THREAD

**Issue by SharkFourSix** [gofika/xlsx#1]
Is it possible to write in a streaming mode? It would be ideal to be able to write rows in a streaming mode. Then you could also be able to configure the in memory buffer threshold.

```go
doc := xlsx.NewFile(xlsx.StreamMode, xlsx.RowBufferSize(100))

defer doc.Close()

pageSize := 100
total := db.GetItemCount()
pages := total / pageSize

if  total % pageSize > 0 {
    pages++
}

sheet := doc.AddSheet("items")
defer sheet.Close()

sheet.AddRow()
    .SetCellValue(xlsx.ColumnNumber("A"),  1, "Name")
    .SetCellValue(xlsx.ColumnNumber("B"),  1, "Quantity")
    .SetCellValue(xlsx.ColumnNumber("C"),  1, "Price")

for page = 0; page < pages; i++ {
    items := db.GetItems(page * pageSize, pageSize)
    for item, _ := range items {
        sheet.AddRow()
            .SetCellValue(xlsx.ColumnNumber("A"),  1, item.Name)
            .SetCellValue(xlsx.ColumnNumber("B"),  1, item.Quantity)
            .SetCellValue(xlsx.ColumnNumber("C"),  1, item.Price)
    }
}

doc.SaveAs("items.xlsx")
```

**Comment by leaker** [comment]
You can use doc.Write to write content as a stream. Here's an example in Go:
```go
package main

import (
	"io"
	"os"

	"github.com/gofika/xlsx"
)

func main() {
	// open file to write
	f, err := os.OpenFile("output.xlsx", os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		panic(err)
	}
	defer f.Close()

	doc := xlsx.NewFile()

	// do something with doc
	// ...

	// write to file or any io.Writer as stream
	doc.Write(f)
}
```

The core goal of my library is to use memory as much as possible to store file data in order to achieve the highest performance.

**Comment by SharkFourSix** [comment]
So you're saying, using `doc.Save` will flush the current data out of memory to the file so I can safely call it multiple times? And what happens to the previously constructed rows? I can save to the file every X amount of rows but I'm not sure if the memory will keep growing

**Comment by leaker** [comment]
**doc.Save** writes out the document data in memory, but it does not clear the current memory information. It is safe to call **doc.Save** multiple times. All building actions are done in memory. Even if you save the file every X lines, the memory will still increase as the document data increases.

The purpose of this library's design is to operate xlsx files with the highest performance, and it is not specifically optimized for small devices such as embedded systems. If you are working with an xlsx document larger than 1GB, it is recommended that your hardware memory be larger than 1GB.
